1. Импортируйте Pandas в Jupyter Notebook.

In [378]:
# напишите свой код тут
import pandas as pd
import numpy as np

# 1. Основыные методы работы с dataframe.

2. Создайте DataFrame из словаря, где ключами будут названия столбцов, а значениями - списки значений этих столбцов.

In [379]:
data = {
    'Name': ['Alica', 'Boris', 'Slava', 'Dmitriy', 'Evgenia','Boris','Dmitriy'],
    'last_name':['Larin','Ivanov','Sidorov','Alekseev','Petrov', 'Lebedev', 'Aksenov'],
    'Age': [24, 27, 22, 32, 29, 44, 15],
    'City': ['Moscow', 'Moscow', 'Saint Peterburg', np.nan, 'Moscow', 'Saint Peterburg','Saint Peterburg'],
    'is_closed': [False, True, False, True, False,  True, False],
    'home_town':['Samara', 'Saratov', 'Saint Peterburg', np.nan, 'Moscow', 'Moscow','Kirov'],
    'in_group':[True, True, False, False, True, True, False],
    'male_dummy':[0, 1, 1, 1, 0, 1, 1],
    'likes_memes':[5, 8, 44, np.nan, 1, 12, 11]
}

In [380]:
# напишите свой код тут
import pandas as pd
s = pd.DataFrame(data)
print(s)

      Name last_name  Age             City  is_closed        home_town  \
0    Alica     Larin   24           Moscow      False           Samara
1    Boris    Ivanov   27           Moscow       True          Saratov
2    Slava   Sidorov   22  Saint Peterburg      False  Saint Peterburg
3  Dmitriy  Alekseev   32              NaN       True              NaN
4  Evgenia    Petrov   29           Moscow      False           Moscow
5    Boris   Lebedev   44  Saint Peterburg       True           Moscow
6  Dmitriy   Aksenov   15  Saint Peterburg      False            Kirov

   in_group  male_dummy  likes_memes
0      True           0          5.0
1      True           1          8.0
2     False           1         44.0
3     False           1          NaN
4      True           0          1.0
5      True           1         12.0
6     False           1         11.0

3. Сохраните DataFrame в CSV-файл.

Сохраните созданный датафрейм в файл people.csv (.to_csv()).

In [381]:
# напишите свой код тут
s.to_csv("people.csv",index=False)

4. Загрузите данные из созданного CSV-файла people.csv в новый DataFrame с именем df и проверьте его содержимое с помощью командой pd.read_csv().

Аргументов у нее очень много, критически важные:

- filepath_or_buffer - текстовая строка с названием (адресом) файла
- sep - разделитель между данными
- header - номер строки, в которой в файле указаны названия столбцов, None, если нет
- names - список с названиями колонок
- index_col - или номер столбца, или список, или ничего - названия строк

In [382]:
# напишите свой код тут
df = pd.read_csv("people.csv")
print(df)

      Name last_name  Age             City  is_closed        home_town  \
0    Alica     Larin   24           Moscow      False           Samara
1    Boris    Ivanov   27           Moscow       True          Saratov
2    Slava   Sidorov   22  Saint Peterburg      False  Saint Peterburg
3  Dmitriy  Alekseev   32              NaN       True              NaN
4  Evgenia    Petrov   29           Moscow      False           Moscow
5    Boris   Lebedev   44  Saint Peterburg       True           Moscow
6  Dmitriy   Aksenov   15  Saint Peterburg      False            Kirov

   in_group  male_dummy  likes_memes
0      True           0          5.0
1      True           1          8.0
2     False           1         44.0
3     False           1          NaN
4      True           0          1.0
5      True           1         12.0
6     False           1         11.0

---

Есть несколько методов, которые мы используем сразу, как загрузили файл:
- [head()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html): выводит первые 5 строк таблицы. Если задать в скобках число, то покажет ровно столько строк :)
- [info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html): показывает сводную информацию о таблице; сколько записей, сколько колонок, сколько непустых записей в таблице,
- [tail()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html): работает как head(), только наоборот, печатает с конца

На всякий случай, это **методы**. Их можно применять к датафрейму и столбцу, т.е. используем их так: <br>
**[Имя датафрейма].[Название метода с круглыми скобками]**
- df.head()
- df.tail()
- df.info()

----


На основную информацию по столбцам можно посмотреть с помощью метода `.info()`. Напротив каждого названия столбца можно увидеть, сколько в нём заполненных ячеек.

5. Выведите на экран первые и последние 3 строки DataFrame.

In [383]:
# напишите свой код тут
print(df.head(3))

    Name last_name  Age             City  is_closed        home_town  \
0  Alica     Larin   24           Moscow      False           Samara
1  Boris    Ivanov   27           Moscow       True          Saratov
2  Slava   Sidorov   22  Saint Peterburg      False  Saint Peterburg

   in_group  male_dummy  likes_memes
0      True           0          5.0
1      True           1          8.0
2     False           1         44.0

In [384]:
# напишите свой код тут
print(df.tail(3))

      Name last_name  Age             City  is_closed home_town  in_group  \
4  Evgenia    Petrov   29           Moscow      False    Moscow      True
5    Boris   Lebedev   44  Saint Peterburg       True    Moscow      True
6  Dmitriy   Aksenov   15  Saint Peterburg      False     Kirov     False

   male_dummy  likes_memes
4           0          1.0
5           1         12.0
6           1         11.0

6. Получите общую информацию о DataFrame, включая количество строк и столбцов, типы данных и количество ненулевых значений. (метод info)

In [385]:
# напишите свой код тут
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         7 non-null      object
 1   last_name    7 non-null      object
 2   Age          7 non-null      int64
 3   City         6 non-null      object
 4   is_closed    7 non-null      bool
 5   home_town    6 non-null      object
 6   in_group     7 non-null      bool
 7   male_dummy   7 non-null      int64
 8   likes_memes  6 non-null      float64
dtypes: bool(2), float64(1), int64(2), object(4)
memory usage: 538.0+ bytes
None

----------
### Поля
Кроме методов, у датафреймом есть еще поля. Это справочная информация о датафрейме. Список полей
<a href="https://pandas.pydata.org/pandas-docs/stable/reference/frame.html"> здесь </a>.

Чаще всего мы используем поля:
- **columns**: названия колонок
- **index**: названия строк
- **shape**: размеры датафрейма, кол-во строк и столбцов

Использование:

**[Имя датафрейма].[Имя поля]**

- df.columns
- df.index
- df.shape

Обратите внимание: нет круглых скобок!

7. Выясните сколько в таблице строк и столбцов (метод shape).

In [386]:
# напишите свой код тут
print(df.shape)

(7, 9)

8. Выведите на экран названия всех колонок таблицы (метод columns)

In [387]:
# напишите свой код тут
print(df.columns)

Index(['Name', 'last_name', 'Age', 'City', 'is_closed', 'home_town',
       'in_group', 'male_dummy', 'likes_memes'],
      dtype='object')

#2. Базовые навыки по работе с табличками

### Выбор колонки

Чтобы вытащить столбец, у нему нужно через квадратные скобки обратиться по имени.

In [388]:
# цепляем head(), чтобы не получить слишком много напечатанных имен
df['Name'].head()

0      Alica
1      Boris
2      Slava
3    Dmitriy
4    Evgenia
Name: Name, dtype: object

In [389]:
# обратите внимание, что в квадратные скобки мы записали только 1 объект - лист с названиями колонок.
t =df[['City', 'Name']].head()
t

              City     Name
0           Moscow    Alica
1           Moscow    Boris
2  Saint Peterburg    Slava
3              NaN  Dmitriy
4           Moscow  Evgenia

Можно создавать новые колонки. Например, мы можем взять все имена и фамилии, записать их через пробел и положить в новую колонку.

In [390]:
t['first_last_name'] = df['Name'] + ' ' + df['last_name']
t.head()

              City     Name   first_last_name
0           Moscow    Alica       Alica Larin
1           Moscow    Boris      Boris Ivanov
2  Saint Peterburg    Slava     Slava Sidorov
3              NaN  Dmitriy  Dmitriy Alekseev
4           Moscow  Evgenia    Evgenia Petrov

### Выбор подряд идущих строк

Если в квадратных скобках указать диапазон, то можно выбрать несколько строк, идущих друг за другом

In [391]:
df[:2]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0

In [392]:
df[1:4]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN

---
### Уникальные значения и частотые таблицы

Очень частой операцией является нахождение уникальных значений в колонке. В зависимости от задачи есть два метода.
- [unique()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.unique.html): возвращает массив уникальных значений в колонке - к нему можем применять только обычный питон
- [drop_duplicates()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html): удаляет дублирующиеся строчки в датафрейме/колонке и возвращает соответственно датафрейм или колонку - к ним можем дальше применять пандасовские методы

- [value_counts()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html): считает частотную таблицу, т.е. сколько раз мы встретили значение в колонке

9. Вытащите из таблички колону с городом (city), примените к ней метод, который оставит в колонке только уникальные названия городов, `.unique()`.

In [393]:
# напишите свой код тут
df["City"].unique()

array(['Moscow', 'Saint Peterburg', nan], dtype=object)

10. Сколько всего городов есть в данных?

In [394]:
# напишите свой код тут
df["City"].value_counts()

City
Moscow             3
Saint Peterburg    3
Name: count, dtype: int64

11. Найдите количество уникальных значений в каждом столбце DataFrame.

In [395]:
# напишите свой код тут
df.nunique()

Name           5
last_name      7
Age            7
City           2
is_closed      2
home_town      5
in_group       2
male_dummy     2
likes_memes    6
dtype: int64

12. Добавьте новый столбец Salary с произвольными значениями зарплат для каждого человека.

In [396]:
# напишите свой код тут
df["Salary"]=[1000, 2000, 3000, 4000, 5000, 6000, 7000]    
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,1000
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,2000
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0,3000
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,4000
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,5000
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,6000
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,7000

13. Измените значение возраста (столбец Age) для любого одного человека.

In [397]:
# напишите свой код тут
df[0,"Age"] = 123
print(df)

      Name last_name  Age             City  is_closed        home_town  \
0    Alica     Larin   24           Moscow      False           Samara
1    Boris    Ivanov   27           Moscow       True          Saratov
2    Slava   Sidorov   22  Saint Peterburg      False  Saint Peterburg
3  Dmitriy  Alekseev   32              NaN       True              NaN
4  Evgenia    Petrov   29           Moscow      False           Moscow
5    Boris   Lebedev   44  Saint Peterburg       True           Moscow
6  Dmitriy   Aksenov   15  Saint Peterburg      False            Kirov

   in_group  male_dummy  likes_memes  Salary  (0, Age)
0      True           0          5.0    1000       123
1      True           1          8.0    2000       123
2     False           1         44.0    3000       123
3     False           1          NaN    4000       123
4      True           0          1.0    5000       123
5      True           1         12.0    6000       123
6     False           1         11.0    7000       123

14. Какая доля людей закрыла профиль (is_closed)?

In [398]:
# напишите свой код тут
print(df['is_closed'].mean())

0.42857142857142855

15. Отфильтруйте строки DataFrame, где возраст больше 25 лет.

In [399]:
# напишите свой код тут
df[df['Age'] > 25]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)"
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,2000,123
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,4000,123
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,5000,123
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,6000,123

16. Отфильтруйте строки, где город равен "Moscow".

In [400]:
# напишите свой код тут
df[df["City"] == "Moscow"]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)"
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,1000,123
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,2000,123
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,5000,123

17. Попробуйте вытащить ту же самую колонку и посчитать по ней, как часто, какой город встречается в данных, `.value_counts()`

In [401]:
# напишите свой код тут
df["City"].value_counts()

City
Moscow             3
Saint Peterburg    3
Name: count, dtype: int64

18. Выведите на экран $2$ самых популярных городов в датафрейме

In [402]:
# напишите свой код тут
df["City"].value_counts().head(2)

City
Moscow             3
Saint Peterburg    3
Name: count, dtype: int64

19. Сгруппируйте данные по столбцу City и найдите средний возраст людей для каждого города. .groupby()

In [403]:
# напишите свой код тут
df.groupby("City")["Age"].mean()

City
Moscow             26.666667
Saint Peterburg    27.000000
Name: Age, dtype: float64

20. Используйте loc, чтобы выбрать строки с именем "Alica" и "Evgenia" и вывести соответствующие данные.

In [404]:
# напишите свой код ту
tmp=df.loc[df["Name"].isin(["Alica","Evgenia"])]
tmp

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)"
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,1000,123
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,5000,123

21. Используйте loc, чтобы изменить значение зарплаты для человека по имени "Dmitriy" на 70000.

In [405]:
# напишите свой код тут
df.loc[df["Name"]=="Dmitriy","Salary"]=70000
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)"
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,1000,123
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,2000,123
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0,3000,123
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,70000,123
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,5000,123
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,6000,123
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,70000,123

22. Используйте loc, чтобы выбрать и вывести данные всех людей старше 30 лет.

In [406]:
# напишите свой код тут
df.loc[df["Age"] > 30]

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)"
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,70000,123
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,6000,123

23. Сколько уникальных мужских имён встречается?

In [407]:
# напишите свой код тут
df.loc[df["male_dummy"]==1,"Name"].unique()

array(['Boris', 'Slava', 'Dmitriy'], dtype=object)

24. Выведите два самых популярных мужских имени

In [408]:
# напишите свой код тут
df.loc[df["male_dummy"]==1,"Name"].value_counts().head(2)

Name
Boris      2
Dmitriy    2
Name: count, dtype: int64

25. Сколько в среднем лайков ставят под мемы девушки (колонка likes_memes)

In [409]:
# напишите свой код тут
df.loc[df["male_dummy"]==0,"likes_memes"].mean()

np.float64(3.0)

26. Сколько суммарно лайков оставили студенты в группе с мемами?

In [410]:
# напишите свой код тут
df.loc[df["in_group"]==True,"likes_memes"].sum()

np.float64(26.0)

27. Сколько в среднем лайков приходится на одного человека, подписанного на группу (колонка in_group)

In [411]:
# напишите свой код тут
df.loc[df["in_group"]==True,"likes_memes"].mean()

np.float64(6.5)

28. Сколько лайков поставили люди, которые не подписаны на группу?

In [412]:
# напишите свой код тут
df.loc[df["in_group"]==False,"likes_memes"].sum()

np.float64(55.0)

29. Выведите на экран колонки, в которых нет ни одного пропуска.

In [413]:
# напишите свой код тут
df.columns[df.isna().sum()==0].tolist()

['Name',
 'last_name',
 'Age',
 'is_closed',
 'in_group',
 'male_dummy',
 'Salary',
 (0, 'Age')]

30.  Сейчас число лайков измеряется по шкале от $0$ до $44$. В машинном обучении довольно часто возникает желание поменять у данных шкалу, в которой они измерены. Такая процедура называется скалированием. Давайте переведём лайки с отрезка $[0, 44]$ на отрезок $[0, 1]$. Делать это будем по формуле:

        x_new = (x-min)/(max-min)
    
        min = минимальный элемент в столбце
        max = максимальный элемент в столбце
        
Получившийся результат запишем в колонку `like_memes_scal`.

In [414]:
# напишите свой код тут
df["like_memes_scal"] = (df["likes_memes"] - df["likes_memes"].min()) / (df["likes_memes"].max() - df["likes_memes"].min())
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)",like_memes_scal
0,Alica,Larin,24,Moscow,False,Samara,True,0,5.0,1000,123,0.093023
1,Boris,Ivanov,27,Moscow,True,Saratov,True,1,8.0,2000,123,0.162791
2,Slava,Sidorov,22,Saint Peterburg,False,Saint Peterburg,False,1,44.0,3000,123,1.000000
3,Dmitriy,Alekseev,32,NaN,True,NaN,False,1,NaN,70000,123,NaN
4,Evgenia,Petrov,29,Moscow,False,Moscow,True,0,1.0,5000,123,0.000000
5,Boris,Lebedev,44,Saint Peterburg,True,Moscow,True,1,12.0,6000,123,0.255814
6,Dmitriy,Aksenov,15,Saint Peterburg,False,Kirov,False,1,11.0,70000,123,0.232558

31. Найдите суммарную зарплату для каждого города

In [415]:
# напишите свой код тут
df.groupby("City")["Salary"].sum()

City
Moscow              8000
Saint Peterburg    79000
Name: Salary, dtype: int64

32. Используйте where, чтобы заменить все значения возраста, которые меньше 25, на NaN.

In [416]:
# напишите свой код тут
df["Age"].where(df["Age"] < 25, inplace=True, other=np.nan)
df

C:\Users\User\AppData\Local\Temp\ipykernel_29100\3097119258.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].where(df["Age"] < 25, inplace=True, other=np.nan)

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)",like_memes_scal
0,Alica,Larin,24.0,Moscow,False,Samara,True,0,5.0,1000,123,0.093023
1,Boris,Ivanov,NaN,Moscow,True,Saratov,True,1,8.0,2000,123,0.162791
2,Slava,Sidorov,22.0,Saint Peterburg,False,Saint Peterburg,False,1,44.0,3000,123,1.000000
3,Dmitriy,Alekseev,NaN,NaN,True,NaN,False,1,NaN,70000,123,NaN
4,Evgenia,Petrov,NaN,Moscow,False,Moscow,True,0,1.0,5000,123,0.000000
5,Boris,Lebedev,NaN,Saint Peterburg,True,Moscow,True,1,12.0,6000,123,0.255814
6,Dmitriy,Aksenov,15.0,Saint Peterburg,False,Kirov,False,1,11.0,70000,123,0.232558

33. Используйте where, чтобы заменить все значения зарплаты, которые меньше 60000, на 12000.

In [417]:
# напишите свой код тут
df["Salary"] = df["Salary"].where(df["Salary"] >= 60000, other=12000)
df

,Name,last_name,Age,City,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)",like_memes_scal
0,Alica,Larin,24.0,Moscow,False,Samara,True,0,5.0,12000,123,0.093023
1,Boris,Ivanov,NaN,Moscow,True,Saratov,True,1,8.0,12000,123,0.162791
2,Slava,Sidorov,22.0,Saint Peterburg,False,Saint Peterburg,False,1,44.0,12000,123,1.000000
3,Dmitriy,Alekseev,NaN,NaN,True,NaN,False,1,NaN,70000,123,NaN
4,Evgenia,Petrov,NaN,Moscow,False,Moscow,True,0,1.0,12000,123,0.000000
5,Boris,Lebedev,NaN,Saint Peterburg,True,Moscow,True,1,12.0,12000,123,0.255814
6,Dmitriy,Aksenov,15.0,Saint Peterburg,False,Kirov,False,1,11.0,70000,123,0.232558

34. Создайте многоуровневый индекс 'City' и 'Name'

In [428]:
# напишите свой код тут
df = df.set_index(["City", "Name"])
df

                        last_name   Age  is_closed        home_town  in_group  \
City            Name
Moscow          Alica       Larin  24.0      False           Samara      True
                Boris      Ivanov   NaN       True          Saratov      True
Saint Peterburg Slava     Sidorov  22.0      False  Saint Peterburg     False
NaN             Dmitriy  Alekseev   NaN       True              NaN     False
Moscow          Evgenia    Petrov   NaN      False           Moscow      True
Saint Peterburg Boris     Lebedev   NaN       True           Moscow      True
                Dmitriy   Aksenov  15.0      False            Kirov     False

                         male_dummy  likes_memes  Salary  (0, Age)  \
City            Name
Moscow          Alica             0          5.0   12000       123
                Boris             1          8.0   12000       123
Saint Peterburg Slava             1         44.0   12000       123
NaN             Dmitriy           1          NaN   70000       123
Moscow          Evgenia           0          1.0   12000       123
Saint Peterburg Boris             1         12.0   12000       123
                Dmitriy           1         11.0   70000       123

                         like_memes_scal
City            Name
Moscow          Alica           0.093023
                Boris           0.162791
Saint Peterburg Slava           1.000000
NaN             Dmitriy              NaN
Moscow          Evgenia         0.000000
Saint Peterburg Boris           0.255814
                Dmitriy         0.232558

35. Используйте xs, чтобы выбрать данные для города "Moscow"

In [430]:
# напишите свой код тут
df.xs("Moscow")

,last_name,Age,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)",like_memes_scal
Name,,,,,,,,,,
Alica,Larin,24.0,False,Samara,True,0,5.0,12000,123,0.093023
Boris,Ivanov,NaN,True,Saratov,True,1,8.0,12000,123,0.162791
Evgenia,Petrov,NaN,False,Moscow,True,0,1.0,12000,123,0.000000

36. Используйте xs, чтобы выбрать данные для человека с именем "Boris"

In [432]:
# напишите свой код тут
df.xs("Boris", level="Name")

,last_name,Age,is_closed,home_town,in_group,male_dummy,likes_memes,Salary,"(0, Age)",like_memes_scal
City,,,,,,,,,,
Moscow,Ivanov,NaN,True,Saratov,True,1,8.0,12000,123,0.162791
Saint Peterburg,Lebedev,NaN,True,Moscow,True,1,12.0,12000,123,0.255814

37. Вычислите суммарную зарплату всех людей.

In [433]:
# напишите свой код тут
df["Salary"].sum()

np.int64(200000)

38. Вычислите среднюю зарплату всех людей нашего Dataframe.

In [434]:
# напишите свой код тут
df["Salary"].mean()

np.float64(28571.428571428572)

39. Вычислите медиану возраста сотрудников.

In [435]:
# напишите свой код тут
df["Age"].median()

np.float64(22.0)

40. Вычислите стандартное отклонение зарплаты

In [436]:
# напишите свой код тут
df["Salary"].std()

np.float64(28301.102115507463)

41. Вычислите минимальную и максимальную зарплату

In [440]:
# напишите свой код тут
min = df["Salary"].min()
max = df["Salary"].max()
print(min, max)

12000 70000

42. Вычислите минимальный и максимальный возраст сотрудников.

In [443]:
# напишите свой код тут
min = df["Age"].min()
max = df["Age"].max()
print(min, max)
df

15.0 24.0

                        last_name   Age  is_closed        home_town  in_group  \
City            Name
Moscow          Alica       Larin  24.0      False           Samara      True
                Boris      Ivanov   NaN       True          Saratov      True
Saint Peterburg Slava     Sidorov  22.0      False  Saint Peterburg     False
NaN             Dmitriy  Alekseev   NaN       True              NaN     False
Moscow          Evgenia    Petrov   NaN      False           Moscow      True
Saint Peterburg Boris     Lebedev   NaN       True           Moscow      True
                Dmitriy   Aksenov  15.0      False            Kirov     False

                         male_dummy  likes_memes  Salary  (0, Age)  \
City            Name
Moscow          Alica             0          5.0   12000       123
                Boris             1          8.0   12000       123
Saint Peterburg Slava             1         44.0   12000       123
NaN             Dmitriy           1          NaN   70000       123
Moscow          Evgenia           0          1.0   12000       123
Saint Peterburg Boris             1         12.0   12000       123
                Dmitriy           1         11.0   70000       123

                         like_memes_scal
City            Name
Moscow          Alica           0.093023
                Boris           0.162791
Saint Peterburg Slava           1.000000
NaN             Dmitriy              NaN
Moscow          Evgenia         0.000000
Saint Peterburg Boris           0.255814
                Dmitriy         0.232558